import { LegalPage, LegalSection } from '@/components/LegalPage';

export const metadata = {
  title: 'Privacy Policy',
  description:
    'How Swash Studio collects, uses, and protects the information you share through our brief and review forms.',
};

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      updated="Last updated: July 2026"
      intro="Swash Studio (&ldquo;Swash&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) builds websites, brands, and motion. This policy explains what personal information we collect when you use this site, why we collect it, who processes it, and the rights you have over it. We keep it plain, because a privacy policy nobody can read protects nobody."
    >
      <LegalSection heading="Who is responsible for your data">
        <p>
          Swash Studio is the responsible party (data controller) for the
          information collected through this site. You can reach us at{' '}
          <a href="mailto:hello@swash.studio" className="text-ink-700 underline decoration-lime-300 underline-offset-4">hello@swash.studio</a>{' '}
          for anything in this policy, including requests to access or delete your data.
        </p>
      </LegalSection>

      <LegalSection heading="What we collect">
        <p>We only collect what you choose to send us. Specifically:</p>
        <p>
          <strong className="text-ink-700">Brief form.</strong> Your name, email,
          phone number (optional), preferred contact method, and the project
          details you provide: industry, goals, features, timeline, budget,
          brand status, brand colours, reference links, notes, and any logo or
          asset files you upload or link.
        </p>
        <p>
          <strong className="text-ink-700">Review form.</strong> Your name,
          company or project (optional), email, star rating, and review text.
          Your email is used only to verify the review and is never published.
        </p>
        <p>
          <strong className="text-ink-700">Technical data.</strong> When you
          submit a form, our servers briefly process your IP address to prevent
          spam and abuse. The site stores a small amount of data in your
          browser&rsquo;s local storage (a saved draft of your brief and a
          first-visit flag). These are functional only, are not shared, and are
          not advertising cookies.
        </p>
        <p>
          We do not run analytics, advertising trackers, or third-party
          cookies on this site.
        </p>
      </LegalSection>

      <LegalSection heading="Why we use it">
        <p>
          To respond to your enquiry, prepare and deliver your video demo and
          proposal, carry out an engagement if you proceed, publish approved
          reviews (only after we verify them with you), and keep the site
          secure. We do not use your information for automated decision-making
          or profiling.
        </p>
      </LegalSection>

      <LegalSection heading="Who processes it">
        <p>
          We do not sell your data. We share it only with the service providers
          that make this site work:
        </p>
        <p>
          <strong className="text-ink-700">Vercel</strong> hosts the site.{' '}
          <strong className="text-ink-700">Cloudflare</strong> provides DNS and
          email routing. <strong className="text-ink-700">Resend</strong>{' '}
          delivers the emails generated by the forms. These providers process
          data on servers outside South Africa (including the United States and
          European Union), so submitting a form involves a cross-border transfer
          of your information. We only use reputable providers with their own
          security and data-protection commitments.
        </p>
      </LegalSection>

      <LegalSection heading="How long we keep it">
        <p>
          We keep brief and review submissions for as long as needed to respond
          to you and, if you become a client, for the duration of our
          engagement plus a reasonable period for our records. Uploaded files
          are kept only as long as they are useful to your project. Ask us to
          delete your information at any time and we will, unless we are
          required to keep it by law.
        </p>
      </LegalSection>

      <LegalSection heading="Your rights">
        <p>
          Under South Africa&rsquo;s POPIA (and, where it applies, the EU GDPR)
          you can ask us to confirm what we hold about you, correct it, delete
          it, or stop using it. You may also object to processing and, if you
          are unhappy with how we have handled your data, complain to the
          Information Regulator of South Africa. To exercise any of these,
          email{' '}
          <a href="mailto:hello@swash.studio" className="text-ink-700 underline decoration-lime-300 underline-offset-4">hello@swash.studio</a>{' '}
          and we will respond promptly.
        </p>
      </LegalSection>

      <LegalSection heading="Security">
        <p>
          Forms are submitted over encrypted HTTPS, submissions are rate-limited
          and validated, and access to the studio inbox is restricted. No system
          is perfectly secure, but we take reasonable measures to protect what
          you share.
        </p>
      </LegalSection>

      <LegalSection heading="Children">
        <p>
          This site is intended for businesses and adults. We do not knowingly
          collect information from anyone under 18.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to this policy">
        <p>
          If we change how we handle data, we will update this page and its
          &ldquo;last updated&rdquo; date. Material changes will be reflected
          here before they take effect.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
